apiVersion: apps/v1
kind: Deployment
metadata:
  name: quickcart-deployment
  labels:
    app: quickcart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quickcart
  template:
    metadata:
      labels:
        app: quickcart
    spec:
      containers:
      - name: quickcart-app
        image: devops-quickcart:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8501
        envFrom:
        - configMapRef:
            name: quickcart-config
        - secretRef:
            name: quickcart-secret
        volumeMounts:
        - name: db-volume
          mountPath: /data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: db-volume
        persistentVolumeClaim:
          claimName: quickcart-db-pvc
